### ISSUE TITLE
need to some improvements for work on latest Smartgesture

### ISSUE THREAD

**Issue by Kyogre** [SEV007/asus_smartgesture_reload_fix#1]
I have smartgesture version 4.0.24 ([link](https://dlcdnets.asus.com/pub/ASUS/nb/Apps_for_Win10/SmartGesture/SmartGesture_Win10_64_VER4024_DriverOnly.zip)). Current bat won't work because it starts only AsusTPCenter.exe and not starts the utility itself (even tray icon won't appear).
If I am correct, it is easy to fix. You just need to change line
`start AsusTPCenter.exe`
to
`start AsusTPLoader.exe`

Also you can make .bat run automatically after Windows resumes from sleep / hibernation. For that you need to create scheduler task like described in this [ASUS forum thread](https://rog.asus.com/forum/showthread.php?93026-Temporary-fix-for-the-touchpad-bug-on-G752VS).
As described in the thread you need to set Single trigger "On Event" + basic + log: System + Source: Kernel-Power + Event ID: 107. Also don't forget to enable option "Run with highest privileges" and make sure you unchecked "Start only if the computer is on AC power".

**Comment by SEV007** [comment]
Thanks I will check it

**Comment by SEV007** [comment]
Actually now that I remember it was intended to start without the utility and the try icon neither was present.
This was done to prevent some bug and made the software run smoother but wont be an issue to add it.
